export const FETCH_COMMENT_OFFENSES = "FETCH_COMMENT_OFFENSES";
export const FETCH_POST_OFFENSES = "FETCH_POST_OFFENSES";
export const FETCH_USER_OFFENSES = "FETCH_USER_OFFENSES";
export const REPORT_LOADING = "REPORT_LOADING";
export const REPORT_SUCCESS = "REPORT_SUCCESS";
export const REPORT_ERROR = "REPORT_ERROR";
export const REPORT_MESSAGE = "REPORT_MESSAGE";
