export const POST_COMMENT = "POST_COMMENT";
export const SET_USER = "SET_USER";
export const CLEAR_USER = "CLEAR_USER";
export const POST_COMMENT_LOADING = "POST_COMMENT_LOADING";
export const POST_COMMENT_SUCCESS = "POST_COMMENT_SUCCESS";
export const POST_COMMENT_ERROR = "POST_COMMENT_ERROR";
